import { Tracker, ProblemWhen, AnswerType } from "@/types/tracker";
import { getLanguage } from "@/lib/i18n";

export interface LifeStreamTemplate {
  id: string;
  title: string;
  titleRu: string;
  questionText: string;
  questionTextRu: string;
  category: Tracker["category"];
  subcategory?: string;
  answerType: AnswerType;
  periodDays: number;
  threshold: number;
  problemWhen: ProblemWhen;
  adviceAboveThreshold: string;
  adviceAboveThresholdRu: string;
}

export interface LifeStream {
  id: string;
  title: string;
  titleRu: string;
  icon: string;
  description: string;
  descriptionRu: string;
  color: string;
  templates: LifeStreamTemplate[];
}

// MeMap template library — restructured around the user's repositioned
// product story: "memory lies, data doesn't."
//
// 6 clusters mapped to real life decisions, not abstract self-awareness
// buckets. Each cluster solves a specific dilemma a real adult faces:
//   1. Partner — "are we really arguing that often?"
//   2. Parenting — "am I yelling too much at my kid?"
//   3. Health & Symptoms — "is this getting worse? show the doctor."
//   4. Habits in Question — "wine every evening, is that a problem?"
//   5. Inner State — "am I actually happy?"
//   6. Big Life Decisions — "do I really want a child / to leave / to switch?"
//
// Templates are STARTING POINTS, not the full menu. The product invites
// users to add their own custom trackers ("called my mom?", "did I cry?",
// "did I exercise?") — these built-ins are illustrative.
//
// All bilingual (EN + RU). Russian uses bracketed gendered forms
// ("Сделал(а)") that polishRu resolves at display time based on the
// user's `pol` setting. Storage keeps the bracketed RAW form so changing
// gender later re-renders correctly.
export const LIFE_STREAMS: LifeStream[] = [
  // ─────────────────────────────────────────────────────────────────
  // 1. PARTNER & LOVED ONES
  // ─────────────────────────────────────────────────────────────────
  {
    id: "partner",
    title: "Partner & Loved Ones",
    titleRu: "Партнёр и близкие",
    icon: "❤️",
    description: "Are we really fighting that often, or does it just feel that way?",
    descriptionRu: "Правда ли мы соримся так часто, или мне просто кажется?",
    color: "relationships",
    templates: [
      {
        id: "argued-with-partner",
        title: "Argued with partner",
        titleRu: "Поссорился(ась) с партнёром",
        questionText: "Did you have a real argument with your partner today?",
        questionTextRu: "Сегодня была серьёзная ссора с партнёром?",
        category: "Connections",
        subcategory: "Partner",
        answerType: "boolean",
        periodDays: 30,
        threshold: 8,
        problemWhen: "yes",
        adviceAboveThreshold: "Write down what usually triggers fights — the pattern says more than any single argument",
        adviceAboveThresholdRu: "Записать что чаще всего вызывает ссоры — паттерн скажет больше чем сама ссора",
      },
      {
        id: "felt-close-to-partner",
        title: "Felt close to partner",
        titleRu: "Чувствовал(а) близость с партнёром",
        questionText: "Was there a warm moment, intimacy, or a sense of closeness today?",
        questionTextRu: "Был ли тёплый момент — близость, объятия, ощущение «мы вместе»?",
        category: "Connections",
        subcategory: "Partner",
        answerType: "boolean",
        periodDays: 30,
        threshold: 12,
        problemWhen: "no",
        adviceAboveThreshold: "Plan one shared moment this week — no tasks, no phones",
        adviceAboveThresholdRu: "Запланировать один совместный момент на эту неделю — без задач и телефонов",
      },
      {
        id: "felt-lonely-with-partner",
        title: "Felt alone next to them",
        titleRu: "Чувствовал(а) себя одиноким(ой) рядом с ним/ней",
        questionText: "Did you feel emotionally distant from your partner today?",
        questionTextRu: "Чувствовал(а) ли ты эмоциональную дистанцию с партнёром сегодня?",
        category: "Connections",
        subcategory: "Partner",
        answerType: "boolean",
        periodDays: 30,
        threshold: 10,
        problemWhen: "yes",
        adviceAboveThreshold: "Tell them how I'm feeling — not in the heat of an argument, but calmly",
        adviceAboveThresholdRu: "Поговорить о том что я чувствую — не в момент ссоры, спокойно",
      },
      {
        id: "partner-irritated-me",
        title: "Partner irritated me",
        titleRu: "Партнёр раздражал",
        questionText: "Did something about them annoy you today?",
        questionTextRu: "Что-то в нём/ней сегодня бесило?",
        category: "Connections",
        subcategory: "Partner",
        answerType: "boolean",
        periodDays: 30,
        threshold: 15,
        problemWhen: "yes",
        adviceAboveThreshold: "Ask myself: what's under the irritation? Tiredness, hurt, an unmet need?",
        adviceAboveThresholdRu: "Спросить себя: что под раздражением? Усталость, обида, неудовлетворённая потребность?",
      },
      {
        id: "good-time-together",
        title: "Had a good time together",
        titleRu: "Хорошо провели время вдвоём",
        questionText: "Did you share a good moment as a couple today?",
        questionTextRu: "Был сегодня совместный приятный момент?",
        category: "Connections",
        subcategory: "Partner",
        answerType: "boolean",
        periodDays: 30,
        threshold: 12,
        problemWhen: "no",
        adviceAboveThreshold: "Plan a date or shared activity for this week",
        adviceAboveThresholdRu: "Запланировать свидание или совместное занятие на эту неделю",
      },
      {
        id: "called-parent",
        title: "Called mom or dad",
        titleRu: "Позвонил(а) маме или папе",
        questionText: "Did you call or check in with a parent today?",
        questionTextRu: "Позвонил(а) или написал(а) маме/папе сегодня?",
        category: "Connections",
        subcategory: "Family",
        answerType: "boolean",
        periodDays: 30,
        threshold: 10,
        problemWhen: "no",
        adviceAboveThreshold: "Set a weekly reminder to call my parents",
        adviceAboveThresholdRu: "Поставить еженедельное напоминание звонить родителям",
      },
      {
        id: "thought-about-leaving",
        title: "Thought about leaving",
        titleRu: "Думал(а) расстаться / разойтись",
        questionText: "Did the thought 'I want out of this relationship' come up today?",
        questionTextRu: "Сегодня была мысль «я хочу уйти из этих отношений»?",
        category: "Connections",
        subcategory: "Partner",
        answerType: "boolean",
        periodDays: 60,
        threshold: 20,
        problemWhen: "yes",
        adviceAboveThreshold: "Talk to a couples therapist — not after a fight, but when calm",
        adviceAboveThresholdRu: "Поговорить с парой-психологом — не после ссоры, а когда спокойно",
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  // 2. PARENTING
  // ─────────────────────────────────────────────────────────────────
  {
    id: "parenting",
    title: "Parenting",
    titleRu: "Родительство",
    icon: "👨‍👩‍👧",
    description: "Am I a bad parent, or do I just remember the bad days?",
    descriptionRu: "Я плохая мать, или я просто помню только плохие дни?",
    color: "mood",
    templates: [
      {
        id: "yelled-at-kid",
        title: "Yelled at my kid",
        titleRu: "Накричал(а) на ребёнка",
        questionText: "Did you have an outburst at your child today?",
        questionTextRu: "Была вспышка / срыв на ребёнка сегодня?",
        category: "Connections",
        subcategory: "Kids",
        answerType: "boolean",
        periodDays: 30,
        threshold: 6,
        problemWhen: "yes",
        adviceAboveThreshold: "Find 30 minutes for myself daily — no kid, no tasks, no phone",
        adviceAboveThresholdRu: "Найти 30 минут на себя каждый день — без ребёнка, без задач, без телефона",
      },
      {
        id: "felt-bad-parent",
        title: "Felt like a bad parent",
        titleRu: "Чувствовал(а) себя плохим родителем",
        questionText: "Did the thought 'I'm a bad mother/father' show up today?",
        questionTextRu: "Прибегала ли мысль «я плохая мать / плохой отец» сегодня?",
        category: "Emotions",
        subcategory: "Parenting",
        answerType: "boolean",
        periodDays: 30,
        threshold: 10,
        problemWhen: "yes",
        adviceAboveThreshold: "Write 3 moments I was a good parent this week",
        adviceAboveThresholdRu: "Записать 3 момента когда я была хорошим родителем на этой неделе",
      },
      {
        id: "quality-time-kid",
        title: "Quality time with my kid",
        titleRu: "Качественное время с ребёнком",
        questionText: "Did you have a real, present moment with your child — not 'half-listening while on phone'?",
        questionTextRu: "Был ли полностью включённый момент с ребёнком — не «вполуха пока в телефоне»?",
        category: "Connections",
        subcategory: "Kids",
        answerType: "boolean",
        periodDays: 30,
        threshold: 12,
        problemWhen: "no",
        adviceAboveThreshold: "Block 15 minutes daily for the kid — no phone, no distractions",
        adviceAboveThresholdRu: "Выделить 15 минут в день только на ребёнка — без телефона, без отвлечений",
      },
      {
        id: "ran-out-of-patience",
        title: "Ran out of patience",
        titleRu: "Терпения не хватило",
        questionText: "Did you run out of patience with your child today?",
        questionTextRu: "Сегодня не хватило терпения с ребёнком?",
        category: "Emotions",
        subcategory: "Parenting",
        answerType: "boolean",
        periodDays: 30,
        threshold: 12,
        problemWhen: "yes",
        adviceAboveThreshold: "Audit my routine — sleep, food, help — what needs to shift first?",
        adviceAboveThresholdRu: "Пересмотреть свой режим — сон, еда, помощь — что в первую очередь поменять?",
      },
      {
        id: "felt-overwhelmed-parenting",
        title: "Felt overwhelmed as a parent",
        titleRu: "Не справлял(а)ся как родитель",
        questionText: "Did parenting feel like too much today?",
        questionTextRu: "Сегодня казалось что родительство — это слишком?",
        category: "Emotions",
        subcategory: "Parenting",
        answerType: "boolean",
        periodDays: 30,
        threshold: 12,
        problemWhen: "yes",
        adviceAboveThreshold: "Ask for specific help — partner, family, sitter — concretely, not vaguely",
        adviceAboveThresholdRu: "Попросить конкретную помощь — у партнёра, семьи, бэбиситтера — по делу, не «помоги»",
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  // 3. HEALTH & SYMPTOMS
  // ─────────────────────────────────────────────────────────────────
  {
    id: "health",
    title: "Health & Symptoms",
    titleRu: "Здоровье и симптомы",
    icon: "🩺",
    description: "Is it getting worse — or do I only remember the bad days? Bring data to the doctor.",
    descriptionRu: "Становится хуже — или я только плохие дни помню? Приди к врачу с данными.",
    color: "health",
    templates: [
      {
        id: "headache",
        title: "Had a headache",
        titleRu: "Болела голова",
        questionText: "Did you have a headache today?",
        questionTextRu: "Болела ли сегодня голова?",
        category: "Body",
        subcategory: "Pain",
        answerType: "boolean",
        periodDays: 30,
        threshold: 8,
        problemWhen: "yes",
        adviceAboveThreshold: "Schedule a doctor visit — bring my month's data, not 'it kind of hurts'",
        adviceAboveThresholdRu: "Записаться к терапевту — взять с собой данные за месяц, не «вроде болит»",
      },
      {
        id: "migraine",
        title: "Migraine attack",
        titleRu: "Приступ мигрени",
        questionText: "Was today a real migraine — strong pain, nausea, light sensitivity?",
        questionTextRu: "Была ли сегодня настоящая мигрень — сильная боль, тошнота, чувствительность к свету?",
        category: "Body",
        subcategory: "Migraine",
        answerType: "boolean",
        periodDays: 30,
        threshold: 4,
        problemWhen: "yes",
        adviceAboveThreshold: "Book a neurologist — migraines need a specialist, not self-treatment",
        adviceAboveThresholdRu: "Записаться к неврологу — мигрень требует специалиста, не самолечения",
      },
      {
        id: "back-or-neck-pain",
        title: "Back or neck pain",
        titleRu: "Болела спина или шея",
        questionText: "Did your back or neck hurt today?",
        questionTextRu: "Болела сегодня спина или шея?",
        category: "Body",
        subcategory: "Pain",
        answerType: "boolean",
        periodDays: 30,
        threshold: 10,
        problemWhen: "yes",
        adviceAboveThreshold: "See an osteopath or physiotherapist — bring my data",
        adviceAboveThresholdRu: "Записаться к остеопату или физиотерапевту — взять с собой данные",
      },
      {
        id: "stomach-issues",
        title: "Stomach / GI issues",
        titleRu: "Беспокоил живот / ЖКТ",
        questionText: "Did your stomach hurt, did you feel nauseous, or have any digestive issues today?",
        questionTextRu: "Болел живот, тошнило, или были проблемы с пищеварением?",
        category: "Body",
        subcategory: "Digestion",
        answerType: "boolean",
        periodDays: 30,
        threshold: 10,
        problemWhen: "yes",
        adviceAboveThreshold: "Log what I ate the day before — find the food trigger",
        adviceAboveThresholdRu: "Записывать что ела за сутки до — ищем еду-триггер",
      },
      {
        id: "joint-pain",
        title: "Joint pain",
        titleRu: "Болели суставы",
        questionText: "Did any joint hurt today (knees, wrists, fingers, etc.)?",
        questionTextRu: "Болел сегодня какой-то сустав (колени, запястья, пальцы)?",
        category: "Body",
        subcategory: "Pain",
        answerType: "boolean",
        periodDays: 30,
        threshold: 8,
        problemWhen: "yes",
        adviceAboveThreshold: "See a rheumatologist — joint pain isn't to be ignored",
        adviceAboveThresholdRu: "Записаться к ревматологу — боль в суставах не игнорируется",
      },
      {
        id: "slept-enough",
        title: "Slept enough (7+ hours)",
        titleRu: "Спал(а) достаточно (7+ часов)",
        questionText: "Did you sleep at least 7 hours and feel rested?",
        questionTextRu: "Спал(а) ли минимум 7 часов и чувствовал(а) себя отдохнувшим(ей)?",
        category: "Health",
        subcategory: "Sleep",
        answerType: "boolean",
        periodDays: 30,
        threshold: 18,
        problemWhen: "no",
        adviceAboveThreshold: "Set a 'bedtime' alarm 8 hours before wake-up — for one week",
        adviceAboveThresholdRu: "Поставить будильник «спать» за 8 часов до подъёма — на неделю",
      },
      {
        id: "felt-fatigued",
        title: "Felt drained all day",
        titleRu: "Чувствовал(а) усталость весь день",
        questionText: "Did you feel exhausted for most of the day?",
        questionTextRu: "Большую часть дня чувствовал(а) себя выжатым(ой)?",
        category: "Body",
        subcategory: "Energy",
        answerType: "boolean",
        periodDays: 30,
        threshold: 12,
        problemWhen: "yes",
        adviceAboveThreshold: "Get bloodwork — iron, ferritin, B12, thyroid panel",
        adviceAboveThresholdRu: "Сдать кровь — железо, ферритин, B12, щитовидка",
      },
      {
        id: "period-symptoms",
        title: "Strong cycle symptoms",
        titleRu: "Сильные симптомы цикла",
        questionText: "Did you have strong period or PMS symptoms today (cramps, mood, bloating)?",
        questionTextRu: "Были ли сегодня сильные симптомы цикла или ПМС (боли, настроение, отёки)?",
        category: "Body",
        subcategory: "Cycle",
        answerType: "boolean",
        periodDays: 30,
        threshold: 8,
        problemWhen: "yes",
        adviceAboveThreshold: "See a gynaecologist — severe PMS isn't 'normal', it can be addressed",
        adviceAboveThresholdRu: "Записаться к гинекологу — сильный ПМС не «норма», его можно скорректировать",
      },
      {
        id: "exercised",
        title: "Worked out",
        titleRu: "Тренировался(ась)",
        questionText: "Did you do a real workout today (gym, run, sport, yoga)?",
        questionTextRu: "Была сегодня настоящая тренировка (зал, бег, спорт, йога)?",
        category: "Health",
        subcategory: "Movement",
        answerType: "boolean",
        periodDays: 30,
        threshold: 12,
        problemWhen: "no",
        adviceAboveThreshold: "Book 3 workout slots in my calendar this week — specific times",
        adviceAboveThresholdRu: "Внести 3 тренировки в календарь на эту неделю — конкретное время",
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  // 4. HABITS IN QUESTION
  // ─────────────────────────────────────────────────────────────────
  {
    id: "habits",
    title: "Habits in Question",
    titleRu: "Привычки в вопросе",
    icon: "🍷",
    description: "'Wine every evening' — really every? Data settles the question.",
    descriptionRu: "«Бокал вина каждый вечер» — правда каждый? Данные ответят честно.",
    color: "custom",
    templates: [
      {
        id: "drank-alcohol",
        title: "Had alcohol",
        titleRu: "Пил(а) алкоголь",
        questionText: "Did you drink any alcohol today (even one glass)?",
        questionTextRu: "Пил(а) ли сегодня алкоголь (даже один бокал)?",
        category: "Health",
        subcategory: "Alcohol",
        answerType: "boolean",
        periodDays: 30,
        threshold: 12,
        problemWhen: "yes",
        adviceAboveThreshold: "Think about what I'm chasing in those evenings — stress, boredom, loneliness, habit?",
        adviceAboveThresholdRu: "Подумать что я ловлю в эти вечера — стресс, скуку, одиночество, привычку?",
      },
      {
        id: "smoked",
        title: "Smoked / vaped",
        titleRu: "Курил(а)",
        questionText: "Did you smoke a cigarette, vape, or hookah today?",
        questionTextRu: "Курил(а) сегодня — сигарету, вейп, кальян?",
        category: "Health",
        subcategory: "Smoking",
        answerType: "boolean",
        periodDays: 30,
        threshold: 8,
        problemWhen: "yes",
        adviceAboveThreshold: "Log the situations where I crave it — that's the trigger map",
        adviceAboveThresholdRu: "Записать в каких ситуациях тянет — это карта триггеров",
      },
      {
        id: "coffee-late",
        title: "Coffee after 2pm",
        titleRu: "Кофе после 14:00",
        questionText: "Did you have caffeine after 2pm today?",
        questionTextRu: "Был кофеин после 14:00?",
        category: "Health",
        subcategory: "Caffeine",
        answerType: "boolean",
        periodDays: 30,
        threshold: 12,
        problemWhen: "yes",
        adviceAboveThreshold: "Move my last coffee to noon for one week — watch what happens to sleep",
        adviceAboveThresholdRu: "Перенести последний кофе на 12:00 на неделю — посмотреть на сон",
      },
      {
        id: "ate-sweets",
        title: "Ate sweets / dessert",
        titleRu: "Ел(а) сладкое",
        questionText: "Did you have sweets or dessert today?",
        questionTextRu: "Ел(а) сегодня сладкое?",
        category: "Health",
        subcategory: "Diet",
        answerType: "boolean",
        periodDays: 30,
        threshold: 15,
        problemWhen: "yes",
        adviceAboveThreshold: "Swap dessert for fruit twice a week — see how I feel",
        adviceAboveThresholdRu: "Заменить десерт на фрукт два раза в неделю — посмотреть как себя чувствую",
      },
      {
        id: "screen-time-long",
        title: "Stuck to a screen 4h+",
        titleRu: "Залип(ла) в экран больше 4 часов",
        questionText: "Did you spend 4+ hours on phone/series outside of work today?",
        questionTextRu: "Был сегодня экран больше 4 часов вне работы (телефон, сериалы)?",
        category: "Health",
        subcategory: "Screen",
        answerType: "boolean",
        periodDays: 30,
        threshold: 15,
        problemWhen: "yes",
        adviceAboveThreshold: "Set an app time limit in phone settings — start with the worst offender",
        adviceAboveThresholdRu: "Поставить лимит на самое затягивающее приложение в настройках телефона",
      },
      {
        id: "ate-fast-food",
        title: "Fast food / fast carbs",
        titleRu: "Фастфуд / быстрые углеводы",
        questionText: "Did you eat fast food, baked goods, or other quick carbs today?",
        questionTextRu: "Ел(а) сегодня фастфуд, выпечку или быстрые углеводы?",
        category: "Health",
        subcategory: "Diet",
        answerType: "boolean",
        periodDays: 30,
        threshold: 12,
        problemWhen: "yes",
        adviceAboveThreshold: "Prep two days of meals on Sunday — start small",
        adviceAboveThresholdRu: "Приготовить еду на 2 дня в воскресенье — начать с малого",
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  // 5. INNER STATE
  // ─────────────────────────────────────────────────────────────────
  {
    id: "state",
    title: "Inner State",
    titleRu: "Состояние",
    icon: "☀️",
    description: "Long-term pattern — not how you feel right now.",
    descriptionRu: "Долгосрочный паттерн — не как ты чувствуешь себя прямо сейчас.",
    color: "emotions",
    templates: [
      {
        id: "felt-happy",
        title: "Felt happy",
        titleRu: "Чувствовал(а) себя счастливым(ой)",
        questionText: "Did I feel happy today?",
        questionTextRu: "Чувствовал(а) ли я себя счастливым(ой) сегодня?",
        category: "Emotions",
        subcategory: "Mood",
        answerType: "boolean",
        periodDays: 30,
        threshold: 18,
        problemWhen: "no",
        adviceAboveThreshold: "Write 3 things in my life that drain joy — and pick one to reduce",
        adviceAboveThresholdRu: "Записать 3 вещи в моей жизни что забирают радость — и выбрать одну чтобы уменьшить",
      },
      {
        id: "felt-anxious",
        title: "Felt anxious",
        titleRu: "Чувствовал(а) тревогу",
        questionText: "Did anxiety show up today?",
        questionTextRu: "Приходила тревога сегодня?",
        category: "Emotions",
        subcategory: "Anxiety",
        answerType: "boolean",
        periodDays: 30,
        threshold: 12,
        problemWhen: "yes",
        adviceAboveThreshold: "Schedule a therapy session — bring my data",
        adviceAboveThresholdRu: "Записаться к психотерапевту — взять с собой данные",
      },
      {
        id: "felt-depressed",
        title: "Felt down or empty",
        titleRu: "Чувствовал(а) подавленность",
        questionText: "Did you feel low, flat, or hopeless for most of the day?",
        questionTextRu: "Был день когда ты чувствовал(а) подавленность или пустоту большую часть дня?",
        category: "Emotions",
        subcategory: "Mood",
        answerType: "boolean",
        periodDays: 30,
        threshold: 8,
        problemWhen: "yes",
        adviceAboveThreshold: "Talk to a doctor — please. This isn't 'it'll pass'.",
        adviceAboveThresholdRu: "Поговорить с врачом — пожалуйста. Это не «само пройдёт».",
      },
      {
        id: "felt-angry",
        title: "Felt angry / irritated",
        titleRu: "Чувствовал(а) злость или раздражение",
        questionText: "Did anger or strong irritation come up today?",
        questionTextRu: "Сегодня была злость или сильное раздражение?",
        category: "Emotions",
        subcategory: "Anger",
        answerType: "boolean",
        periodDays: 30,
        threshold: 12,
        problemWhen: "yes",
        adviceAboveThreshold: "Ask myself: what need isn't being met? Anger is just messenger.",
        adviceAboveThresholdRu: "Спросить себя: какая моя потребность не услышана? Злость только сообщает.",
      },
      {
        id: "felt-lonely",
        title: "Felt lonely",
        titleRu: "Чувствовал(а) одиночество",
        questionText: "Did loneliness show up today?",
        questionTextRu: "Сегодня было одиноко?",
        category: "Emotions",
        subcategory: "Loneliness",
        answerType: "boolean",
        periodDays: 30,
        threshold: 10,
        problemWhen: "yes",
        adviceAboveThreshold: "Text one person today — short message, no special reason",
        adviceAboveThresholdRu: "Написать одному человеку сегодня — короткое сообщение, без повода",
      },
      {
        id: "had-energy",
        title: "Had energy",
        titleRu: "Была энергия",
        questionText: "Did you have enough energy to do what you wanted to today?",
        questionTextRu: "Хватило сегодня энергии на то, что хотелось сделать?",
        category: "Emotions",
        subcategory: "Energy",
        answerType: "boolean",
        periodDays: 30,
        threshold: 15,
        problemWhen: "no",
        adviceAboveThreshold: "Get bloodwork — iron, ferritin, B12, thyroid panel",
        adviceAboveThresholdRu: "Сдать кровь — железо, ферритин, B12, щитовидка",
      },
      {
        id: "cried-today",
        title: "Cried today",
        titleRu: "Плакал(а) сегодня",
        questionText: "Did you cry today (even briefly)?",
        questionTextRu: "Сегодня плакал(а) — даже коротко?",
        category: "Emotions",
        subcategory: "Tears",
        answerType: "boolean",
        periodDays: 30,
        threshold: 6,
        problemWhen: "yes",
        adviceAboveThreshold: "Talk to a friend or therapist about what's building up",
        adviceAboveThresholdRu: "Поговорить с подругой или психологом о том что копится",
      },
      {
        id: "burned-out-after-work",
        title: "Burned out after work",
        titleRu: "Выгорал(а) после работы",
        questionText: "Did you feel completely drained after work today?",
        questionTextRu: "Чувствовал(а) полное выгорание после работы?",
        category: "Emotions",
        subcategory: "Burnout",
        answerType: "boolean",
        periodDays: 30,
        threshold: 10,
        problemWhen: "yes",
        adviceAboveThreshold: "Write 3 things at work that drain me — and remove one",
        adviceAboveThresholdRu: "Записать 3 вещи на работе которые забирают энергию — и одну убрать",
      },
      {
        id: "didnt-want-to-work",
        title: "Didn't want to go to work",
        titleRu: "Не хотелось идти на работу",
        questionText: "Did you really not want to go to work today?",
        questionTextRu: "Сегодня по-настоящему не хотелось идти на работу?",
        category: "Voice",
        subcategory: "Motivation",
        answerType: "boolean",
        periodDays: 30,
        threshold: 12,
        problemWhen: "yes",
        adviceAboveThreshold: "Give myself 2 weeks before deciding — and log what bothers me daily",
        adviceAboveThresholdRu: "Дать себе 2 недели перед решением — и каждый день записывать что мешает",
      },
      {
        id: "worked-overtime",
        title: "Worked overtime",
        titleRu: "Перерабатывал(а)",
        questionText: "Did you work significantly longer than planned today?",
        questionTextRu: "Сегодня работал(а) заметно дольше, чем планировал(а)?",
        category: "Voice",
        subcategory: "Overtime",
        answerType: "boolean",
        periodDays: 30,
        threshold: 12,
        problemWhen: "yes",
        adviceAboveThreshold: "Set a hard end-of-day time this week — and stick to it",
        adviceAboveThresholdRu: "Поставить твёрдое время окончания работы на эту неделю — и держаться его",
      },
      {
        id: "felt-fulfilled-at-work",
        title: "Felt fulfilled by work",
        titleRu: "Работа давала энергию",
        questionText: "Did work feel meaningful or energising today?",
        questionTextRu: "Сегодня работа казалась осмысленной или придавала энергию?",
        category: "Voice",
        subcategory: "Meaning",
        answerType: "boolean",
        periodDays: 30,
        threshold: 12,
        problemWhen: "no",
        adviceAboveThreshold: "Have an honest talk with myself: is it the job, or this season of life?",
        adviceAboveThresholdRu: "Поговорить с собой честно: дело в работе или в моменте жизни?",
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  // 6. BIG LIFE DECISIONS
  // ─────────────────────────────────────────────────────────────────
  {
    id: "big-decisions",
    title: "Big Decisions",
    titleRu: "Большие решения",
    icon: "🤔",
    description: "Today you want it, tomorrow you don't. Three months later — you'll know.",
    descriptionRu: "Сегодня хочется, завтра — нет. Через три месяца увидишь как на самом деле.",
    color: "voice",
    templates: [
      {
        id: "wanted-child",
        title: "Wanted a child today",
        titleRu: "Сегодня хотелось ребёнка",
        questionText: "Did the desire to have a child come up today?",
        questionTextRu: "Сегодня было желание иметь ребёнка?",
        category: "Curious",
        subcategory: "Decisions",
        answerType: "boolean",
        periodDays: 90,
        threshold: 35,
        problemWhen: "yes",
        adviceAboveThreshold: "Talk specifics with my partner — money, home, emotional readiness",
        adviceAboveThresholdRu: "Поговорить с партнёром предметно — финансово, бытово, эмоционально",
      },
      {
        id: "thought-about-emigrating",
        title: "Thought about leaving the country",
        titleRu: "Думал(а) уехать из страны",
        questionText: "Did you think about emigrating or moving abroad today?",
        questionTextRu: "Сегодня была мысль уехать / эмигрировать?",
        category: "Curious",
        subcategory: "Decisions",
        answerType: "boolean",
        periodDays: 90,
        threshold: 30,
        problemWhen: "yes",
        adviceAboveThreshold: "Write 3 reasons to leave and 3 to stay — see them on paper",
        adviceAboveThresholdRu: "Записать 3 причины уехать и 3 причины остаться — посмотреть на бумаге",
      },
      {
        id: "wanted-leave-job",
        title: "Wanted to quit my job",
        titleRu: "Хотелось уйти с работы",
        questionText: "Did you think about quitting today?",
        questionTextRu: "Сегодня хотелось уволиться?",
        category: "Curious",
        subcategory: "Decisions",
        answerType: "boolean",
        periodDays: 60,
        threshold: 20,
        problemWhen: "yes",
        adviceAboveThreshold: "Write what specifically wears me down — then I'll know if it's leaving or fixing",
        adviceAboveThresholdRu: "Записать что именно тяготит — потом ясно, уходить или менять",
      },
      {
        id: "thought-divorce",
        title: "Thought about ending it",
        titleRu: "Думал(а) расстаться / развестись",
        questionText: "Did the thought 'I want out of this relationship' come up today?",
        questionTextRu: "Сегодня была мысль «я хочу уйти из этих отношений»?",
        category: "Curious",
        subcategory: "Decisions",
        answerType: "boolean",
        periodDays: 60,
        threshold: 18,
        problemWhen: "yes",
        adviceAboveThreshold: "Book a couples therapist — alone or together — and talk it through",
        adviceAboveThresholdRu: "Записаться к семейному психологу — одной или вдвоём — и обсудить",
      },
      {
        id: "wanted-life-change",
        title: "Wanted a radical change",
        titleRu: "Хотелось радикально менять жизнь",
        questionText: "Did you have a strong urge to overhaul your life today?",
        questionTextRu: "Сегодня было сильное «всё поменять» в жизни?",
        category: "Curious",
        subcategory: "Decisions",
        answerType: "boolean",
        periodDays: 60,
        threshold: 18,
        problemWhen: "yes",
        adviceAboveThreshold: "Write what specifically I want to change — concretely, not 'everything'",
        adviceAboveThresholdRu: "Записать что именно хочу изменить — конкретно, не «всё»",
      },
      {
        id: "wanted-pet",
        title: "Wanted to get a pet",
        titleRu: "Хотелось завести питомца",
        questionText: "Did you want to get a cat / dog / pet today?",
        questionTextRu: "Сегодня хотелось завести кошку / собаку / питомца?",
        category: "Curious",
        subcategory: "Decisions",
        answerType: "boolean",
        periodDays: 60,
        threshold: 25,
        problemWhen: "yes",
        adviceAboveThreshold: "Visit a shelter — look, sit with it, see the real picture",
        adviceAboveThresholdRu: "Сходить в приют — посмотреть, посидеть, увидеть реальную картину",
      },
      {
        id: "wanted-learn-new",
        title: "Wanted to learn / change career",
        titleRu: "Хотелось учиться / новой профессии",
        questionText: "Did you think about learning something new or switching field today?",
        questionTextRu: "Сегодня думал(а) о новом обучении или смене профессии?",
        category: "Curious",
        subcategory: "Decisions",
        answerType: "boolean",
        periodDays: 60,
        threshold: 25,
        problemWhen: "yes",
        adviceAboveThreshold: "Find one course or book this week — try without commitment",
        adviceAboveThresholdRu: "Найти один курс или книгу на эту неделю — попробовать без обязательств",
      },
    ],
  },
];

export interface LocalizedTemplate {
  id: string;
  title: string;
  questionText: string;
  category: Tracker["category"];
  subcategory?: string;
  answerType: AnswerType;
  periodDays: number;
  threshold: number;
  problemWhen: ProblemWhen;
  adviceAboveThreshold: string;
}

export const localizeTemplate = (tpl: LifeStreamTemplate): LocalizedTemplate => {
  const isRu = getLanguage() === "ru";
  return {
    id: tpl.id,
    title: isRu ? tpl.titleRu : tpl.title,
    questionText: isRu ? tpl.questionTextRu : tpl.questionText,
    category: tpl.category,
    subcategory: tpl.subcategory,
    answerType: tpl.answerType,
    periodDays: tpl.periodDays,
    threshold: tpl.threshold,
    problemWhen: tpl.problemWhen,
    adviceAboveThreshold: isRu ? tpl.adviceAboveThresholdRu : tpl.adviceAboveThreshold,
  };
};

export const localizeStream = (stream: LifeStream) => {
  const isRu = getLanguage() === "ru";
  return {
    ...stream,
    title: isRu ? stream.titleRu : stream.title,
    description: isRu ? stream.descriptionRu : stream.description,
  };
};

// Get 3-5 random templates for "Ideas of the day" (localized to active language)
export const getRandomIdeas = (count: number = 4): (LocalizedTemplate & { streamIcon: string; streamColor: string })[] => {
  const allTemplates = LIFE_STREAMS.flatMap(stream =>
    stream.templates.map(t => ({
      ...localizeTemplate(t),
      streamIcon: stream.icon,
      streamColor: stream.color,
    }))
  );
  const shuffled = [...allTemplates].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
};

// Static "trending" questions surfaced as conversation starters in the
// app. Picked to span the new positioning: relationship, parenting,
// habit, big-decision, emotional-honesty.
const TRENDING_TEMPLATES_RAW: LifeStreamTemplate[] = [
  {
    id: "trending-argued",
    title: "Argued with partner",
    titleRu: "Поссорился(ась) с партнёром",
    questionText: "Did you have a real argument with your partner today?",
    questionTextRu: "Сегодня была серьёзная ссора с партнёром?",
    category: "Connections",
    subcategory: "Partner",
    answerType: "boolean",
    periodDays: 30,
    threshold: 8,
    problemWhen: "yes",
    adviceAboveThreshold: "Write down what usually triggers fights — the pattern says more than any single argument",
    adviceAboveThresholdRu: "Записать что чаще всего вызывает ссоры — паттерн скажет больше чем сама ссора",
  },
  {
    id: "trending-yelled",
    title: "Yelled at my kid",
    titleRu: "Накричал(а) на ребёнка",
    questionText: "Did you have an outburst at your child today?",
    questionTextRu: "Была вспышка / срыв на ребёнка сегодня?",
    category: "Connections",
    subcategory: "Kids",
    answerType: "boolean",
    periodDays: 30,
    threshold: 6,
    problemWhen: "yes",
    adviceAboveThreshold: "Find 30 minutes for myself daily — no kid, no tasks, no phone",
    adviceAboveThresholdRu: "Найти 30 минут на себя каждый день — без ребёнка, без задач, без телефона",
  },
  {
    id: "trending-alcohol",
    title: "Had alcohol",
    titleRu: "Пил(а) алкоголь",
    questionText: "Did you drink any alcohol today (even one glass)?",
    questionTextRu: "Пил(а) ли сегодня алкоголь (даже один бокал)?",
    category: "Health",
    subcategory: "Alcohol",
    answerType: "boolean",
    periodDays: 30,
    threshold: 12,
    problemWhen: "yes",
    adviceAboveThreshold: "Think about what I'm chasing in those evenings — stress, boredom, loneliness, habit?",
    adviceAboveThresholdRu: "Подумать что я ловлю в эти вечера — стресс, скуку, одиночество, привычку?",
  },
  {
    id: "trending-cried",
    title: "Cried today",
    titleRu: "Плакал(а) сегодня",
    questionText: "Did you cry today (even briefly)?",
    questionTextRu: "Сегодня плакал(а) — даже коротко?",
    category: "Emotions",
    subcategory: "Tears",
    answerType: "boolean",
    periodDays: 30,
    threshold: 6,
    problemWhen: "yes",
    adviceAboveThreshold: "Talk to a friend or therapist about what's building up",
    adviceAboveThresholdRu: "Поговорить с подругой или психологом о том что копится",
  },
  {
    id: "trending-wanted-child",
    title: "Wanted a child today",
    titleRu: "Сегодня хотелось ребёнка",
    questionText: "Did the desire to have a child come up today?",
    questionTextRu: "Сегодня было желание иметь ребёнка?",
    category: "Curious",
    subcategory: "Decisions",
    answerType: "boolean",
    periodDays: 90,
    threshold: 35,
    problemWhen: "yes",
    adviceAboveThreshold: "Talk specifics with my partner — money, home, emotional readiness",
    adviceAboveThresholdRu: "Поговорить с партнёром предметно — финансово, бытово, эмоционально",
  },
];

// Public export: raw templates (for title/question lookup maps)
export const TRENDING_TEMPLATES_SOURCE = TRENDING_TEMPLATES_RAW;

// Public export: localized for rendering (call at render time so language changes apply)
export const getTrendingTemplates = (): LocalizedTemplate[] =>
  TRENDING_TEMPLATES_RAW.map(localizeTemplate);
