import { Tracker, ProblemWhen, AnswerType } from "@/types/tracker";
import { getLanguage } from "@/lib/i18n";

export interface LifeStreamTemplate {
  id: string;
  title: string;
  titleRu: string;
  questionText: string;
  questionTextRu: string;
  category: Tracker["category"];
  subcategory?: string;
  answerType: AnswerType;
  periodDays: number;
  threshold: number;
  problemWhen: ProblemWhen;
  adviceAboveThreshold: string;
  adviceAboveThresholdRu: string;
}

export interface LifeStream {
  id: string;
  title: string;
  titleRu: string;
  icon: string;
  description: string;
  descriptionRu: string;
  color: string;
  templates: LifeStreamTemplate[];
}

export const LIFE_STREAMS: LifeStream[] = [
  {
    id: "emotions-mind",
    title: "Emotions & Mind",
    titleRu: "Эмоции и разум",
    icon: "🧠",
    description: "Notice your inner weather",
    descriptionRu: "Замечай свою внутреннюю погоду",
    color: "mood",
    templates: [
      {
        id: "morning-mood",
        title: "Woke up rested",
        titleRu: "Проснулся(ась) отдохнувшим",
        questionText: "Did you wake up feeling rested?",
        questionTextRu: "Ты проснулся(ась) сегодня отдохнувшим?",
        category: "Emotions",
        answerType: "boolean",
        periodDays: 30,
        threshold: 15,
        problemWhen: "no",
        adviceAboveThreshold: "Mornings often feel heavy. Consider your sleep routine or evening habits.",
        adviceAboveThresholdRu: "Утра часто даются тяжело. Подумай о режиме сна и вечерних привычках.",
      },
      {
        id: "anxious-today",
        title: "Anxious today?",
        titleRu: "Тревожно сегодня?",
        questionText: "Did anxiety show up today?",
        questionTextRu: "Приходила ли сегодня тревога?",
        category: "Emotions",
        answerType: "boolean",
        periodDays: 30,
        threshold: 15,
        problemWhen: "yes",
        adviceAboveThreshold: "Anxiety appearing frequently. It might help to talk to someone.",
        adviceAboveThresholdRu: "Тревога появляется часто. Возможно, стоит с кем-то поговорить.",
      },
      {
        id: "happy-today",
        title: "Felt happy today",
        titleRu: "Чувствовал(а) себя счастливым(ой)",
        questionText: "Did you feel happy today?",
        questionTextRu: "Чувствовал(а) ли ты себя сегодня счастливым(ой)?",
        category: "Emotions",
        answerType: "boolean",
        periodDays: 30,
        threshold: 10,
        problemWhen: "no",
        adviceAboveThreshold: "Happy days are rare lately. What's been weighing on you?",
        adviceAboveThresholdRu: "Радостных дней мало в последнее время. Что тебя гнетёт?",
      },
      {
        id: "brain-fog",
        title: "Brain fog",
        titleRu: "Туман в голове",
        questionText: "Did you feel noticeable brain fog today?",
        questionTextRu: "Чувствовал(а) ли ты сегодня заметный туман в голове?",
        category: "Emotions",
        answerType: "boolean",
        periodDays: 30,
        threshold: 15,
        problemWhen: "yes",
        adviceAboveThreshold: "Brain fog is frequent. Check sleep, stress levels, or nutrition.",
        adviceAboveThresholdRu: "Туман в голове частый. Проверь сон, уровень стресса и питание.",
      },
      {
        id: "creative-spark",
        title: "Creative moment",
        titleRu: "Творческий момент",
        questionText: "Did you feel a creative spark today?",
        questionTextRu: "Ощущал(а) ли ты сегодня творческую искру?",
        category: "Emotions",
        answerType: "boolean",
        periodDays: 30,
        threshold: 20,
        problemWhen: "no",
        adviceAboveThreshold: "Creativity feels rare lately. Try changing your routine or surroundings.",
        adviceAboveThresholdRu: "Творчества в последнее время мало. Попробуй сменить рутину или обстановку.",
      },
      {
        id: "cried-today",
        title: "Cried today",
        titleRu: "Сегодня плакал(а)",
        questionText: "Did I cry today?",
        questionTextRu: "Я сегодня плакал(а)?",
        category: "Emotions",
        answerType: "boolean",
        periodDays: 30,
        threshold: 12,
        problemWhen: "yes",
        adviceAboveThreshold: "Notice this pattern — what might it tell you?",
        adviceAboveThresholdRu: "Заметь эту закономерность — что она может тебе сказать?",
      },
      {
        id: "felt-gratitude",
        title: "Felt gratitude",
        titleRu: "Чувствовал(а) благодарность",
        questionText: "Did I feel gratitude for something today?",
        questionTextRu: "Я чувствовал(а) за что-то благодарность сегодня?",
        category: "Emotions",
        answerType: "boolean",
        periodDays: 30,
        threshold: 20,
        problemWhen: "no",
        adviceAboveThreshold: "Gratitude is rare. Small moments of appreciation can shift perspective.",
        adviceAboveThresholdRu: "Благодарность появляется редко. Маленькие моменты признательности меняют взгляд.",
      },
      {
        id: "anxious-no-reason",
        title: "Anxious for no reason",
        titleRu: "Тревога без причины",
        questionText: "Did I feel anxious for no reason?",
        questionTextRu: "Я чувствовал(а) тревогу без причины?",
        category: "Emotions",
        answerType: "boolean",
        periodDays: 30,
        threshold: 12,
        problemWhen: "yes",
        adviceAboveThreshold: "Unexplained anxiety is frequent. Worth exploring with support.",
        adviceAboveThresholdRu: "Необъяснимая тревога — частая. Стоит разобраться с поддержкой специалиста.",
      },
      {
        id: "felt-inspired",
        title: "Felt inspired",
        titleRu: "Чувствовал(а) вдохновение",
        questionText: "Did I feel inspired today?",
        questionTextRu: "Я чувствовал(а) сегодня вдохновение?",
        category: "Emotions",
        answerType: "boolean",
        periodDays: 30,
        threshold: 20,
        problemWhen: "no",
        adviceAboveThreshold: "Inspiration feels absent. New experiences might help.",
        adviceAboveThresholdRu: "Вдохновения почти нет. Новые впечатления могут помочь.",
      },
      {
        id: "wanted-child",
        title: "Wanted to have a child",
        titleRu: "Хотел(а) завести ребёнка",
        questionText: "Did I want to have a child today?",
        questionTextRu: "Я хотел(а) сегодня завести ребёнка?",
        category: "Emotions",
        answerType: "boolean",
        periodDays: 30,
        threshold: 10,
        problemWhen: "yes",
        adviceAboveThreshold: "This feeling appears often. Worth reflecting deeply.",
        adviceAboveThresholdRu: "Это чувство появляется часто. Стоит поразмышлять над ним глубже.",
      },
      {
        id: "emotionally-empty",
        title: "Felt emotionally empty",
        titleRu: "Эмоциональная пустота",
        questionText: "Did I feel emotionally empty?",
        questionTextRu: "Я чувствовал(а) эмоциональную пустоту?",
        category: "Emotions",
        answerType: "boolean",
        periodDays: 30,
        threshold: 12,
        problemWhen: "yes",
        adviceAboveThreshold: "Emptiness is showing up. Consider reaching out for support.",
        adviceAboveThresholdRu: "Пустота даёт о себе знать. Подумай о том, чтобы обратиться за поддержкой.",
      },
      {
        id: "wanted-disappear",
        title: "Wanted to be alone",
        titleRu: "Хотел(а) побыть один",
        questionText: "Did I strongly want to be left alone today?",
        questionTextRu: "Мне сегодня сильно хотелось, чтобы меня оставили в покое?",
        category: "Emotions",
        answerType: "boolean",
        periodDays: 30,
        threshold: 12,
        problemWhen: "yes",
        adviceAboveThreshold: "Wanting to withdraw is recurring. Worth checking in with someone you trust.",
        adviceAboveThresholdRu: "Желание уйти в себя возвращается часто. Стоит поговорить с тем, кому доверяешь.",
      },
      {
        id: "laughed-out-loud",
        title: "Laughed out loud",
        titleRu: "Смеялся(ась) в голос",
        questionText: "Did I laugh out loud?",
        questionTextRu: "Я сегодня громко смеялся(ась)?",
        category: "Emotions",
        answerType: "boolean",
        periodDays: 30,
        threshold: 20,
        problemWhen: "no",
        adviceAboveThreshold: "Laughter is rare. Joy might need more space.",
        adviceAboveThresholdRu: "Смеха мало. Возможно, радости нужно больше места в твоей жизни.",
      },
    ],
  },
  {
    id: "body-sensations",
    title: "Body & Sensations",
    titleRu: "Тело и ощущения",
    icon: "✨",
    description: "Listen to your body's signals",
    descriptionRu: "Слушай сигналы своего тела",
    color: "health",
    templates: [
      {
        id: "headache-days",
        title: "Headache today",
        titleRu: "Сегодня голова болела",
        questionText: "Did you have a headache today?",
        questionTextRu: "У тебя сегодня болела голова?",
        category: "Body",
        answerType: "boolean",
        periodDays: 60,
        threshold: 15,
        problemWhen: "yes",
        adviceAboveThreshold: "Frequent headaches. Consider tracking triggers or seeing a doctor.",
        adviceAboveThresholdRu: "Головные боли частые. Стоит отслеживать триггеры или обратиться к врачу.",
      },
      {
        id: "energy-level",
        title: "Felt energized",
        titleRu: "Чувствовал(а) энергию",
        questionText: "Did you feel energized today?",
        questionTextRu: "Ты чувствовал(а) сегодня прилив энергии?",
        category: "Body",
        answerType: "boolean",
        periodDays: 30,
        threshold: 15,
        problemWhen: "no",
        adviceAboveThreshold: "Low energy is common for you. Look at sleep, movement, and rest.",
        adviceAboveThresholdRu: "Низкая энергия — твоя норма. Обрати внимание на сон, движение и отдых.",
      },
      {
        id: "stomach-issues",
        title: "Stomach bothered me",
        titleRu: "Беспокоил живот",
        questionText: "Did your stomach bother you today?",
        questionTextRu: "Тебя сегодня беспокоил живот?",
        category: "Body",
        answerType: "boolean",
        periodDays: 30,
        threshold: 12,
        problemWhen: "yes",
        adviceAboveThreshold: "Your stomach often feels off. Worth tracking what you eat or stress levels.",
        adviceAboveThresholdRu: "Живот часто даёт сбой. Стоит отслеживать еду и уровень стресса.",
      },
      {
        id: "body-felt-good",
        title: "Body felt good",
        titleRu: "Тело ощущалось хорошо",
        questionText: "Did your body feel comfortable and good today?",
        questionTextRu: "Тело ощущалось сегодня комфортно и хорошо?",
        category: "Body",
        answerType: "boolean",
        periodDays: 30,
        threshold: 20,
        problemWhen: "no",
        adviceAboveThreshold: "Your body rarely feels good. Small movement or stretching might help.",
        adviceAboveThresholdRu: "Тело редко чувствует себя хорошо. Немного движения или растяжки могут помочь.",
      },
      {
        id: "pain-level",
        title: "Physical pain",
        titleRu: "Физическая боль",
        questionText: "Did you feel significant physical pain today?",
        questionTextRu: "Ты чувствовал(а) сегодня заметную физическую боль?",
        category: "Body",
        answerType: "boolean",
        periodDays: 30,
        threshold: 10,
        problemWhen: "yes",
        adviceAboveThreshold: "Pain is frequent. Consider tracking what triggers it or seeking help.",
        adviceAboveThresholdRu: "Боль появляется часто. Стоит отследить триггеры или обратиться за помощью.",
      },
      {
        id: "painful-cramps",
        title: "Painful cramps",
        titleRu: "Болезненные спазмы",
        questionText: "Did I have painful cramps today?",
        questionTextRu: "У меня сегодня были болезненные спазмы?",
        category: "Body",
        answerType: "boolean",
        periodDays: 30,
        threshold: 12,
        problemWhen: "yes",
        adviceAboveThreshold: "Cramps are frequent. Track the pattern and consider medical advice.",
        adviceAboveThresholdRu: "Спазмы частые. Отслеживай закономерность и подумай о консультации врача.",
      },
      {
        id: "stumbled-tripped",
        title: "Stumbled or tripped",
        titleRu: "Спотыкался(ась) или падал(а)",
        questionText: "Did I stumble or trip?",
        questionTextRu: "Я сегодня спотыкался(ась) или чуть не упал(а)?",
        category: "Body",
        answerType: "boolean",
        periodDays: 30,
        threshold: 10,
        problemWhen: "yes",
        adviceAboveThreshold: "Frequent stumbling. Worth checking balance or environment.",
        adviceAboveThresholdRu: "Часто спотыкаешься. Стоит проверить равновесие или осмотреть пространство.",
      },
      {
        id: "felt-dizzy",
        title: "Felt dizzy",
        titleRu: "Кружилась голова",
        questionText: "Did I feel dizzy?",
        questionTextRu: "У меня сегодня кружилась голова?",
        category: "Body",
        answerType: "boolean",
        periodDays: 30,
        threshold: 10,
        problemWhen: "yes",
        adviceAboveThreshold: "Dizziness is common. Consider hydration, sleep, or medical check.",
        adviceAboveThresholdRu: "Головокружения частые. Обрати внимание на воду, сон или сходи к врачу.",
      },
      {
        id: "back-hurt",
        title: "Back hurt",
        titleRu: "Болела спина",
        questionText: "Did my back hurt?",
        questionTextRu: "У меня сегодня болела спина?",
        category: "Body",
        answerType: "boolean",
        periodDays: 30,
        threshold: 15,
        problemWhen: "yes",
        adviceAboveThreshold: "Back pain is regular. Posture, movement, or support might help.",
        adviceAboveThresholdRu: "Спина болит регулярно. Помогут осанка, движение или поддержка специалиста.",
      },
      {
        id: "tired-after-eating",
        title: "Tired after eating",
        titleRu: "Уставал(а) после еды",
        questionText: "Did I feel tired after eating?",
        questionTextRu: "Я чувствовал(а) усталость после еды?",
        category: "Body",
        answerType: "boolean",
        periodDays: 30,
        threshold: 12,
        problemWhen: "yes",
        adviceAboveThreshold: "Post-meal fatigue is common. Food choices might be a factor.",
        adviceAboveThresholdRu: "Усталость после еды частая. Возможно, дело в том, что ты ешь.",
      },
    ],
  },
  {
    id: "connections-love",
    title: "Connections & Love",
    titleRu: "Связи и любовь",
    icon: "❤️",
    description: "Track your relationship patterns",
    descriptionRu: "Отслеживай закономерности в отношениях",
    color: "relationships",
    templates: [
      {
        id: "felt-loved",
        title: "Felt loved",
        titleRu: "Чувствовал(а) себя любимым",
        questionText: "Did you feel loved today?",
        questionTextRu: "Ты чувствовал(а) себя сегодня любимым?",
        category: "Connections",
        answerType: "boolean",
        periodDays: 30,
        threshold: 15,
        problemWhen: "no",
        adviceAboveThreshold: "Love feels distant lately. Small gestures or open conversation might help.",
        adviceAboveThresholdRu: "Любовь кажется далёкой. Маленькие жесты или откровенный разговор могут помочь.",
      },
      {
        id: "reached-out",
        title: "Reached out to someone",
        titleRu: "Связался(ась) с кем-то",
        questionText: "Did you reach out to a friend or loved one?",
        questionTextRu: "Ты написал(а) или позвонил(а) другу либо близкому?",
        category: "Connections",
        answerType: "boolean",
        periodDays: 30,
        threshold: 20,
        problemWhen: "no",
        adviceAboveThreshold: "You're rarely reaching out. Connection takes effort, even a quick message helps.",
        adviceAboveThresholdRu: "Ты редко пишешь первым. Связь требует усилий — даже короткое сообщение помогает.",
      },
      {
        id: "argued-with-partner",
        title: "Argued with partner",
        titleRu: "Ссорился(ась) с партнёром",
        questionText: "Did you argue with your partner today?",
        questionTextRu: "Ты сегодня ссорился(ась) с партнёром?",
        category: "Connections",
        answerType: "boolean",
        periodDays: 30,
        threshold: 10,
        problemWhen: "yes",
        adviceAboveThreshold: "Arguments are frequent. Open, calm conversations or therapy might help.",
        adviceAboveThresholdRu: "Ссоры частые. Помогут спокойные откровенные разговоры или парная терапия.",
      },
      {
        id: "felt-lonely",
        title: "Felt lonely",
        titleRu: "Чувствовал(а) одиночество",
        questionText: "Did you feel lonely today?",
        questionTextRu: "Ты чувствовал(а) сегодня одиночество?",
        category: "Connections",
        answerType: "boolean",
        periodDays: 30,
        threshold: 15,
        problemWhen: "yes",
        adviceAboveThreshold: "Loneliness is showing up often. Small social steps or new routines could shift this.",
        adviceAboveThresholdRu: "Одиночество появляется часто. Маленькие социальные шаги могут это изменить.",
      },
      {
        id: "quality-time",
        title: "Quality time",
        titleRu: "Качественное время",
        questionText: "Did you spend real quality time with someone you care about?",
        questionTextRu: "Ты провёл(а) настоящее качественное время с близким человеком?",
        category: "Connections",
        answerType: "boolean",
        periodDays: 30,
        threshold: 18,
        problemWhen: "no",
        adviceAboveThreshold: "Quality time is rare. Even short moments of presence can make a difference.",
        adviceAboveThresholdRu: "Качественного времени мало. Даже короткие моменты присутствия имеют значение.",
      },
      {
        id: "partner-flowers",
        title: "Got an affectionate gesture",
        titleRu: "Получил(а) жест внимания",
        questionText: "Did my partner do something affectionate for me today (gift, note, hug, kind word)?",
        questionTextRu: "Партнёр сделал сегодня для меня что-то приятное (подарок, записка, объятие, доброе слово)?",
        category: "Connections",
        answerType: "boolean",
        periodDays: 30,
        threshold: 22,
        problemWhen: "no",
        adviceAboveThreshold: "Affectionate gestures feel rare. Love languages vary — name what you need.",
        adviceAboveThresholdRu: "Жестов внимания мало. Языки любви разные — назови, что тебе нужно.",
      },
      {
        id: "anyone-hug",
        title: "Anyone hug me",
        titleRu: "Меня кто-то обнял",
        questionText: "Did anyone hug me today?",
        questionTextRu: "Меня сегодня кто-нибудь обнял?",
        category: "Connections",
        answerType: "boolean",
        periodDays: 30,
        threshold: 18,
        problemWhen: "no",
        adviceAboveThreshold: "Physical touch is rare. Ask for what you need.",
        adviceAboveThresholdRu: "Тактильных прикосновений мало. Проси о том, в чём нуждаешься.",
      },
      {
        id: "called-friend",
        title: "Called a friend",
        titleRu: "Звонил(а) другу",
        questionText: "Did I call a friend today?",
        questionTextRu: "Я сегодня звонил(а) другу?",
        category: "Connections",
        answerType: "boolean",
        periodDays: 30,
        threshold: 20,
        problemWhen: "no",
        adviceAboveThreshold: "You're not reaching out. Connection needs initiative.",
        adviceAboveThresholdRu: "Ты не выходишь на связь. Общение требует инициативы.",
      },
      {
        id: "friend-called-first",
        title: "Friend called me first",
        titleRu: "Друг позвонил первым",
        questionText: "Did a friend call me first?",
        questionTextRu: "Мне сегодня первым позвонил друг?",
        category: "Connections",
        answerType: "boolean",
        periodDays: 30,
        threshold: 20,
        problemWhen: "no",
        adviceAboveThreshold: "Others rarely initiate. Friendships need mutual effort.",
        adviceAboveThresholdRu: "Другие редко пишут первыми. Дружба требует взаимных усилий.",
      },
      {
        id: "close-to-partner",
        title: "Felt close to partner",
        titleRu: "Чувствовал(а) близость с партнёром",
        questionText: "Did I feel close to my partner?",
        questionTextRu: "Я чувствовал(а) сегодня близость с партнёром?",
        category: "Connections",
        answerType: "boolean",
        periodDays: 30,
        threshold: 18,
        problemWhen: "no",
        adviceAboveThreshold: "Distance is common. Small conversations can rebuild closeness.",
        adviceAboveThresholdRu: "Дистанция частая. Маленькие разговоры восстанавливают близость.",
      },
      {
        id: "unexpected-smile",
        title: "Someone made me smile",
        titleRu: "Кто-то заставил улыбнуться",
        questionText: "Did anyone make me smile unexpectedly?",
        questionTextRu: "Кто-то неожиданно заставил меня сегодня улыбнуться?",
        category: "Connections",
        answerType: "boolean",
        periodDays: 30,
        threshold: 20,
        problemWhen: "no",
        adviceAboveThreshold: "Joy from others is rare. Open yourself to small moments.",
        adviceAboveThresholdRu: "Радость от других — редкость. Открывайся маленьким моментам.",
      },
      {
        id: "time-family",
        title: "Spent time with family",
        titleRu: "Провёл(а) время с семьёй",
        questionText: "Did I spend time with family?",
        questionTextRu: "Я провёл(а) сегодня время с семьёй?",
        category: "Connections",
        answerType: "boolean",
        periodDays: 30,
        threshold: 20,
        problemWhen: "no",
        adviceAboveThreshold: "Family time is infrequent. Even brief check-ins matter.",
        adviceAboveThresholdRu: "Времени с семьёй мало. Даже короткие созвоны имеют значение.",
      },
    ],
  },
  {
    id: "voice-behavior",
    title: "Voice & Behavior",
    titleRu: "Голос и поведение",
    icon: "🗣️",
    description: "Notice how you show up",
    descriptionRu: "Замечай, каким ты приходишь к людям",
    color: "work",
    templates: [
      {
        id: "spoke-my-truth",
        title: "Spoke my truth",
        titleRu: "Говорил(а) свою правду",
        questionText: "Did you say what you really meant today?",
        questionTextRu: "Ты сегодня сказал(а) то, что на самом деле думал(а)?",
        category: "Voice",
        answerType: "boolean",
        periodDays: 30,
        threshold: 20,
        problemWhen: "no",
        adviceAboveThreshold: "You're often holding back. Small honest moments build courage.",
        adviceAboveThresholdRu: "Ты часто сдерживаешься. Маленькие честные моменты растят смелость.",
      },
      {
        id: "interrupted-someone",
        title: "Interrupted others",
        titleRu: "Перебивал(а) других",
        questionText: "Did you interrupt someone while they were talking?",
        questionTextRu: "Ты сегодня перебивал(а) кого-то во время разговора?",
        category: "Voice",
        answerType: "boolean",
        periodDays: 30,
        threshold: 10,
        problemWhen: "yes",
        adviceAboveThreshold: "Interrupting is a habit. Try pausing and listening fully before speaking.",
        adviceAboveThresholdRu: "Перебивать — привычка. Попробуй сначала выслушивать до конца.",
      },
      {
        id: "apologized-today",
        title: "Apologized today",
        titleRu: "Извинялся(ась) сегодня",
        questionText: "Did I apologize for something today?",
        questionTextRu: "Я сегодня за что-то извинялся(ась)?",
        category: "Voice",
        answerType: "boolean",
        periodDays: 30,
        threshold: 15,
        problemWhen: "yes",
        adviceAboveThreshold: "You apologize often. Worth noticing if it's a pattern, not always real fault.",
        adviceAboveThresholdRu: "Ты часто извиняешься. Замечай, не привычка ли это, а не реальная вина.",
      },
      {
        id: "raised-voice",
        title: "Raised my voice",
        titleRu: "Повышал(а) голос",
        questionText: "Did you raise your voice or yell today?",
        questionTextRu: "Ты сегодня повышал(а) голос или кричал(а)?",
        category: "Voice",
        answerType: "boolean",
        periodDays: 30,
        threshold: 8,
        problemWhen: "yes",
        adviceAboveThreshold: "Yelling happens frequently. Stress or boundaries might need attention.",
        adviceAboveThresholdRu: "Крики случаются часто. Возможно, дело в стрессе или границах.",
      },
      {
        id: "said-no",
        title: "Said no",
        titleRu: "Сказал(а) нет",
        questionText: "Did you say 'no' to something you didn't want to do?",
        questionTextRu: "Ты сегодня сказал(а) «нет» тому, чего не хотел(а) делать?",
        category: "Voice",
        answerType: "boolean",
        periodDays: 30,
        threshold: 20,
        problemWhen: "no",
        adviceAboveThreshold: "You rarely say no. Boundaries are self-care, not selfishness.",
        adviceAboveThresholdRu: "Ты редко говоришь «нет». Границы — это забота о себе, а не эгоизм.",
      },
      {
        id: "swore-today",
        title: "Swore today",
        titleRu: "Ругался(ась) матом",
        questionText: "Did I swear today?",
        questionTextRu: "Я сегодня ругался(ась) матом?",
        category: "Voice",
        answerType: "boolean",
        periodDays: 30,
        threshold: 15,
        problemWhen: "yes",
        adviceAboveThreshold: "Swearing is frequent. Notice what triggers it.",
        adviceAboveThresholdRu: "Ругаешься часто. Замечай, что это провоцирует.",
      },
      {
        id: "complimented-someone",
        title: "Complimented someone",
        titleRu: "Сделал(а) комплимент",
        questionText: "Did I compliment someone?",
        questionTextRu: "Я сегодня сделал(а) кому-то комплимент?",
        category: "Voice",
        answerType: "boolean",
        periodDays: 30,
        threshold: 20,
        problemWhen: "no",
        adviceAboveThreshold: "Compliments are rare. Kind words create connection.",
        adviceAboveThresholdRu: "Комплиментов мало. Добрые слова создают связь.",
      },
      {
        id: "said-sorry-first",
        title: "Said sorry first",
        titleRu: "Извинился(ась) первым",
        questionText: "Did I say 'sorry' first?",
        questionTextRu: "Я сегодня извинился(ась) первым?",
        category: "Voice",
        answerType: "boolean",
        periodDays: 30,
        threshold: 15,
        problemWhen: "yes",
        adviceAboveThreshold: "You apologize first often. Worth noticing if it's necessary.",
        adviceAboveThresholdRu: "Ты часто извиняешься первым. Стоит подумать, всегда ли это нужно.",
      },
      {
        id: "stayed-calm",
        title: "Stayed calm instead of reacting",
        titleRu: "Оставался(ась) спокойным вместо реакции",
        questionText: "Did I manage to stay calm instead of reacting?",
        questionTextRu: "Мне удалось остаться спокойным, а не реагировать?",
        category: "Voice",
        answerType: "boolean",
        periodDays: 30,
        threshold: 20,
        problemWhen: "no",
        adviceAboveThreshold: "Reactive moments are common. Pausing helps.",
        adviceAboveThresholdRu: "Реактивные моменты — частые. Помогает пауза.",
      },
      {
        id: "said-no-without-guilt",
        title: "Said no without guilt",
        titleRu: "Сказал(а) нет без вины",
        questionText: "Did I say 'no' without guilt?",
        questionTextRu: "Я сказал(а) «нет» без чувства вины?",
        category: "Voice",
        answerType: "boolean",
        periodDays: 30,
        threshold: 20,
        problemWhen: "no",
        adviceAboveThreshold: "Guilt often follows 'no.' Your needs matter too.",
        adviceAboveThresholdRu: "После «нет» часто приходит вина. Твои потребности тоже важны.",
      },
    ],
  },
  {
    id: "health-routine",
    title: "Health & Routine",
    titleRu: "Здоровье и рутина",
    icon: "🏃",
    description: "Track daily habits and rhythms",
    descriptionRu: "Отслеживай ежедневные привычки и ритмы",
    color: "health",
    templates: [
      {
        id: "slept-well",
        title: "Slept well",
        titleRu: "Хорошо выспался(ась)",
        questionText: "Did you sleep well last night?",
        questionTextRu: "Ты хорошо спал(а) этой ночью?",
        category: "Health",
        answerType: "boolean",
        periodDays: 30,
        threshold: 18,
        problemWhen: "no",
        adviceAboveThreshold: "Sleep is often poor. Small changes to your evening routine could help.",
        adviceAboveThresholdRu: "Сон часто плохой. Маленькие изменения вечерней рутины могут помочь.",
      },
      {
        id: "moved-body",
        title: "Moved my body",
        titleRu: "Двигался(ась)",
        questionText: "Did you intentionally move your body today (walk, stretch, dance)?",
        questionTextRu: "Ты сегодня намеренно двигался(ась) (ходил(а), тянулся(ась), танцевал(а))?",
        category: "Health",
        answerType: "boolean",
        periodDays: 30,
        threshold: 20,
        problemWhen: "no",
        adviceAboveThreshold: "Movement is rare. Even 10 minutes of walking can shift your mood.",
        adviceAboveThresholdRu: "Движения мало. Даже 10 минут ходьбы меняют настроение.",
      },
      {
        id: "water-intake",
        title: "Drank enough water",
        titleRu: "Пил(а) достаточно воды",
        questionText: "Did you drink enough water today?",
        questionTextRu: "Ты сегодня пил(а) достаточно воды?",
        category: "Health",
        answerType: "boolean",
        periodDays: 30,
        threshold: 18,
        problemWhen: "no",
        adviceAboveThreshold: "Hydration is often low. A water bottle nearby makes it easier.",
        adviceAboveThresholdRu: "Часто пьёшь мало. Бутылка воды под рукой помогает.",
      },
      {
        id: "caffeine-count",
        title: "High caffeine day",
        titleRu: "День с большим кофеином",
        questionText: "Did you have more than 2 caffeinated drinks today?",
        questionTextRu: "У тебя сегодня было больше 2 напитков с кофеином?",
        category: "Health",
        answerType: "boolean",
        periodDays: 30,
        threshold: 15,
        problemWhen: "yes",
        adviceAboveThreshold: "Caffeine intake is high on many days. Consider reducing gradually.",
        adviceAboveThresholdRu: "Кофеина много в большинстве дней. Попробуй постепенно уменьшать.",
      },
      {
        id: "ate-mindfully",
        title: "Ate mindfully",
        titleRu: "Ел(а) осознанно",
        questionText: "Did you eat at least one meal without screens or rushing?",
        questionTextRu: "Ты ел(а) хотя бы один раз без экранов и без спешки?",
        category: "Health",
        answerType: "boolean",
        periodDays: 30,
        threshold: 20,
        problemWhen: "no",
        adviceAboveThreshold: "Mindful eating is rare. Slowing down even once a day helps.",
        adviceAboveThresholdRu: "Осознанно ешь редко. Замедляться хотя бы раз в день — уже помогает.",
      },
      {
        id: "medication-helped",
        title: "Medication helped",
        titleRu: "Лекарство помогло",
        questionText: "Did my medication help today?",
        questionTextRu: "Моё лекарство сегодня помогло?",
        category: "Health",
        answerType: "boolean",
        periodDays: 30,
        threshold: 15,
        problemWhen: "no",
        adviceAboveThreshold: "Medication often doesn't help. Discuss with your doctor.",
        adviceAboveThresholdRu: "Лекарство часто не помогает. Обсуди это с врачом.",
      },
      {
        id: "felt-side-effects",
        title: "Felt side effects",
        titleRu: "Чувствовал(а) побочные эффекты",
        questionText: "Did I feel side effects?",
        questionTextRu: "Я чувствовал(а) побочные эффекты?",
        category: "Health",
        answerType: "boolean",
        periodDays: 30,
        threshold: 12,
        problemWhen: "yes",
        adviceAboveThreshold: "Side effects are frequent. Worth medical review.",
        adviceAboveThresholdRu: "Побочные эффекты частые. Стоит показаться врачу.",
      },
      {
        id: "pills-on-time",
        title: "Took pills on time",
        titleRu: "Принимал(а) таблетки вовремя",
        questionText: "Did I take my pills on time?",
        questionTextRu: "Я принял(а) сегодня таблетки вовремя?",
        category: "Health",
        answerType: "boolean",
        periodDays: 30,
        threshold: 15,
        problemWhen: "no",
        adviceAboveThreshold: "Medication timing is inconsistent. Set reminders.",
        adviceAboveThresholdRu: "Приём непостоянный. Поставь напоминания.",
      },
    ],
  },
  {
    id: "curious-random",
    title: "Curious & Random",
    titleRu: "Любопытное и случайное",
    icon: "🔍",
    description: "Track life's little mysteries",
    descriptionRu: "Отслеживай маленькие загадки жизни",
    color: "custom",
    templates: [
      {
        id: "learned-something",
        title: "Learned something new",
        titleRu: "Узнал(а) что-то новое",
        questionText: "Did you learn something new today?",
        questionTextRu: "Ты сегодня узнал(а) что-то новое?",
        category: "Curious",
        answerType: "boolean",
        periodDays: 30,
        threshold: 20,
        problemWhen: "no",
        adviceAboveThreshold: "Learning feels rare. Curiosity feeds the mind. Try one new thing.",
        adviceAboveThresholdRu: "Узнаёшь новое редко. Любопытство кормит ум — попробуй одно новое дело.",
      },
      {
        id: "random-kindness",
        title: "Random kindness",
        titleRu: "Случайная доброта",
        questionText: "Did you do something kind for a stranger?",
        questionTextRu: "Ты сделал(а) сегодня что-то доброе для незнакомца?",
        category: "Curious",
        answerType: "boolean",
        periodDays: 30,
        threshold: 25,
        problemWhen: "no",
        adviceAboveThreshold: "Kindness to strangers is rare. Small acts create connection.",
        adviceAboveThresholdRu: "Добра к незнакомцам мало. Маленькие поступки создают связь.",
      },
      {
        id: "noticed-nature",
        title: "Noticed nature",
        titleRu: "Замечал(а) природу",
        questionText: "Did you notice something beautiful in nature today?",
        questionTextRu: "Ты заметил(а) сегодня что-то красивое в природе?",
        category: "Curious",
        answerType: "boolean",
        periodDays: 30,
        threshold: 20,
        problemWhen: "no",
        adviceAboveThreshold: "Nature feels invisible. Even a tree outside the window counts.",
        adviceAboveThresholdRu: "Природа как будто невидима. Даже дерево за окном — уже много.",
      },
      {
        id: "lucky-moments",
        title: "Lucky moments",
        titleRu: "Удачные моменты",
        questionText: "Did something lucky or coincidental happen?",
        questionTextRu: "Случилось ли что-то удачное или совпадение?",
        category: "Curious",
        answerType: "boolean",
        periodDays: 30,
        threshold: 25,
        problemWhen: "no",
        adviceAboveThreshold: "Luck feels rare. Maybe you're not noticing the small wins.",
        adviceAboveThresholdRu: "Удачи будто мало. Возможно, ты не замечаешь маленькие победы.",
      },
      {
        id: "changed-mind",
        title: "Changed my mind",
        titleRu: "Поменял(а) мнение",
        questionText: "Did you change your mind about something today?",
        questionTextRu: "Ты сегодня поменял(а) о чём-то своё мнение?",
        category: "Curious",
        answerType: "boolean",
        periodDays: 30,
        threshold: 25,
        problemWhen: "no",
        adviceAboveThreshold: "You rarely change your mind. Flexibility is growth.",
        adviceAboveThresholdRu: "Ты редко меняешь мнение. Гибкость — это рост.",
      },
      {
        id: "weird-dream",
        title: "Had a weird dream",
        titleRu: "Видел(а) странный сон",
        questionText: "Did I have a weird dream?",
        questionTextRu: "Мне снился странный сон?",
        category: "Curious",
        answerType: "boolean",
        periodDays: 30,
        threshold: 25,
        problemWhen: "no",
        adviceAboveThreshold: "Dreams feel absent. Notice them when you wake.",
        adviceAboveThresholdRu: "Сны будто исчезли. Замечай их сразу после пробуждения.",
      },
      {
        id: "beautiful-street",
        title: "Saw something beautiful",
        titleRu: "Видел(а) что-то красивое",
        questionText: "Did I see something beautiful on the street?",
        questionTextRu: "Я видел(а) сегодня что-то красивое на улице?",
        category: "Curious",
        answerType: "boolean",
        periodDays: 30,
        threshold: 20,
        problemWhen: "no",
        adviceAboveThreshold: "Beauty feels invisible. Slow down and look around.",
        adviceAboveThresholdRu: "Красота будто невидима. Замедлись и оглянись.",
      },
      {
        id: "found-lost-something",
        title: "Found or lost something",
        titleRu: "Нашёл(а) или потерял(а) что-то",
        questionText: "Did I find or lose something small?",
        questionTextRu: "Я сегодня что-то маленькое нашёл(а) или потерял(а)?",
        category: "Curious",
        answerType: "boolean",
        periodDays: 30,
        threshold: 25,
        problemWhen: "no",
        adviceAboveThreshold: "Little losses and finds go unnoticed. They're part of life's rhythm.",
        adviceAboveThresholdRu: "Маленькие потери и находки остаются незамеченными. Это ритм жизни.",
      },
      {
        id: "deja-vu",
        title: "Experienced déjà vu",
        titleRu: "Ощутил(а) дежавю",
        questionText: "Did I experience déjà vu?",
        questionTextRu: "Я сегодня ощутил(а) дежавю?",
        category: "Curious",
        answerType: "boolean",
        periodDays: 30,
        threshold: 25,
        problemWhen: "no",
        adviceAboveThreshold: "Déjà vu is rare. Brain's glitches are curious.",
        adviceAboveThresholdRu: "Дежавю случается редко. Сбои мозга — любопытная штука.",
      },
      {
        id: "funny-phrase",
        title: "Heard a funny phrase",
        titleRu: "Слышал(а) забавную фразу",
        questionText: "Did I hear a funny phrase today?",
        questionTextRu: "Я слышал(а) сегодня забавную фразу?",
        category: "Curious",
        answerType: "boolean",
        periodDays: 30,
        threshold: 20,
        problemWhen: "no",
        adviceAboveThreshold: "Language delights are missed. Listen more closely.",
        adviceAboveThresholdRu: "Радости языка проходят мимо. Слушай внимательнее.",
      },
    ],
  },
  {
    id: "fun-weird",
    title: "Fun & Weird",
    titleRu: "Весёлое и странное",
    icon: "🎭",
    description: "Life's absurd moments",
    descriptionRu: "Абсурдные моменты жизни",
    color: "custom",
    templates: [
      {
        id: "laughed-hard",
        title: "Laughed really hard",
        titleRu: "Очень сильно смеялся(ась)",
        questionText: "Did you laugh so hard you cried or snorted?",
        questionTextRu: "Ты сегодня смеялся(ась) так, что плакал(а) или фыркал(а)?",
        category: "Fun",
        answerType: "boolean",
        periodDays: 30,
        threshold: 20,
        problemWhen: "no",
        adviceAboveThreshold: "Hard laughter is rare. Joy might need more space in your life.",
        adviceAboveThresholdRu: "Громкий смех редок. Радости нужно больше места в твоей жизни.",
      },
      {
        id: "made-joke",
        title: "Made someone laugh",
        titleRu: "Рассмешил(а) кого-то",
        questionText: "Did you make someone laugh today?",
        questionTextRu: "Ты сегодня кого-нибудь рассмешил(а)?",
        category: "Fun",
        answerType: "boolean",
        periodDays: 30,
        threshold: 20,
        problemWhen: "no",
        adviceAboveThreshold: "You're not making others laugh much. Playfulness is connection.",
        adviceAboveThresholdRu: "Ты мало смешишь других. Игривость — это связь.",
      },
      {
        id: "wore-bright-colors",
        title: "Wore bright colors",
        titleRu: "Носил(а) яркие цвета",
        questionText: "Did you wear bright or fun colors today?",
        questionTextRu: "Ты надел(а) сегодня что-то яркое или весёлое по цвету?",
        category: "Fun",
        answerType: "boolean",
        periodDays: 30,
        threshold: 20,
        problemWhen: "no",
        adviceAboveThreshold: "Your wardrobe feels muted. Color can shift mood before you speak.",
        adviceAboveThresholdRu: "Гардероб приглушённый. Цвет меняет настроение ещё до слов.",
      },
      {
        id: "sang-out-loud",
        title: "Sang out loud",
        titleRu: "Пел(а) вслух",
        questionText: "Did you sing out loud today (even badly)?",
        questionTextRu: "Ты сегодня пел(а) вслух (пусть даже плохо)?",
        category: "Fun",
        answerType: "boolean",
        periodDays: 30,
        threshold: 20,
        problemWhen: "no",
        adviceAboveThreshold: "Singing is rare. Let your voice out, it's freeing.",
        adviceAboveThresholdRu: "Поёшь редко. Выпускай голос — это освобождает.",
      },
      {
        id: "danced-no-music",
        title: "Danced with no music",
        titleRu: "Танцевал(а) без музыки",
        questionText: "Did I dance with no music?",
        questionTextRu: "Я сегодня танцевал(а) без музыки?",
        category: "Fun",
        answerType: "boolean",
        periodDays: 30,
        threshold: 25,
        problemWhen: "no",
        adviceAboveThreshold: "Spontaneous dance is absent. Let loose sometimes.",
        adviceAboveThresholdRu: "Спонтанных танцев нет. Иногда просто отпускай себя.",
      },
      {
        id: "sang-shower",
        title: "Sang in the shower",
        titleRu: "Пел(а) в душе",
        questionText: "Did I sing in the shower?",
        questionTextRu: "Я сегодня пел(а) в душе?",
        category: "Fun",
        answerType: "boolean",
        periodDays: 30,
        threshold: 20,
        problemWhen: "no",
        adviceAboveThreshold: "Shower concerts are rare. Joy in small moments matters.",
        adviceAboveThresholdRu: "Концерты в душе редки. Радость в мелочах имеет значение.",
      },
      {
        id: "imagined-movie-character",
        title: "Imagined myself as movie character",
        titleRu: "Представлял(а) себя киногероем",
        questionText: "Did I imagine myself as a movie character?",
        questionTextRu: "Я представлял(а) себя сегодня героем фильма?",
        category: "Fun",
        answerType: "boolean",
        periodDays: 30,
        threshold: 25,
        problemWhen: "no",
        adviceAboveThreshold: "Fantasy feels absent. Imagination is playfulness.",
        adviceAboveThresholdRu: "Фантазии будто нет. Воображение — это игра.",
      },
      {
        id: "made-meme",
        title: "Made a meme about my day",
        titleRu: "Сделал(а) мем про свой день",
        questionText: "Did I make a meme about my day?",
        questionTextRu: "Я сделал(а) сегодня мем про свой день?",
        category: "Fun",
        answerType: "boolean",
        periodDays: 30,
        threshold: 25,
        problemWhen: "no",
        adviceAboveThreshold: "Humor about life is rare. Laughing at yourself helps.",
        adviceAboveThresholdRu: "Юмора про свою жизнь мало. Смеяться над собой — помогает.",
      },
      {
        id: "new-life-feeling",
        title: "Felt like starting new life",
        titleRu: "Хотел(а) начать новую жизнь",
        questionText: "Did I feel like starting a new life somewhere?",
        questionTextRu: "Я хотел(а) сегодня начать новую жизнь где-то ещё?",
        category: "Fun",
        answerType: "boolean",
        periodDays: 30,
        threshold: 12,
        problemWhen: "yes",
        adviceAboveThreshold: "Escape fantasies are frequent. Worth exploring what's missing.",
        adviceAboveThresholdRu: "Фантазии о побеге частые. Стоит понять, чего не хватает.",
      },
    ],
  },
  {
    id: "social-digital",
    title: "Social & Digital",
    titleRu: "Соцсети и цифровое",
    icon: "📱",
    description: "Notice your digital patterns",
    descriptionRu: "Замечай свои цифровые паттерны",
    color: "work",
    templates: [
      {
        id: "doomscrolling",
        title: "Doomscrolling time",
        titleRu: "Залипал(а) в ленте",
        questionText: "Did you spend time doomscrolling or stuck in feeds?",
        questionTextRu: "Ты сегодня залипал(а) в ленте или бесконечно скроллил(а)?",
        category: "Social",
        answerType: "boolean",
        periodDays: 30,
        threshold: 15,
        problemWhen: "yes",
        adviceAboveThreshold: "Doomscrolling is frequent. Try setting boundaries or replacing it.",
        adviceAboveThresholdRu: "Залипания частые. Поставь границы или замени это на что-то другое.",
      },
      {
        id: "posted-online",
        title: "Posted something",
        titleRu: "Что-то выложил(а)",
        questionText: "Did you post anything on social media?",
        questionTextRu: "Ты сегодня что-то выкладывал(а) в соцсетях?",
        category: "Social",
        answerType: "boolean",
        periodDays: 30,
        threshold: 20,
        problemWhen: "yes",
        adviceAboveThreshold: "You post often. Worth noticing why and how it makes you feel.",
        adviceAboveThresholdRu: "Ты постишь часто. Замечай, зачем это и какие чувства даёт.",
      },
      {
        id: "phone-free-hour",
        title: "Phone-free hour",
        titleRu: "Час без телефона",
        questionText: "Did you have at least one hour without your phone?",
        questionTextRu: "У тебя был сегодня хотя бы один час без телефона?",
        category: "Social",
        answerType: "boolean",
        periodDays: 30,
        threshold: 20,
        problemWhen: "no",
        adviceAboveThreshold: "Phone is always present. Even one hour off can feel refreshing.",
        adviceAboveThresholdRu: "Телефон всегда рядом. Даже один час без него освежает.",
      },
      {
        id: "compared-myself",
        title: "Compared myself online",
        titleRu: "Сравнивал(а) себя в сети",
        questionText: "Did you compare yourself to someone online today?",
        questionTextRu: "Ты сегодня сравнивал(а) себя с кем-то в сети?",
        category: "Social",
        answerType: "boolean",
        periodDays: 30,
        threshold: 12,
        problemWhen: "yes",
        adviceAboveThreshold: "Comparison is frequent. Social media shows highlight reels, not reality.",
        adviceAboveThresholdRu: "Сравнения частые. Соцсети показывают выжимку, а не реальность.",
      },
      {
        id: "sent-voice-note",
        title: "Sent a voice note",
        titleRu: "Отправил(а) голосовое",
        questionText: "Did you send a voice message instead of typing?",
        questionTextRu: "Ты сегодня отправил(а) голосовое вместо того, чтобы напечатать?",
        category: "Social",
        answerType: "boolean",
        periodDays: 30,
        threshold: 25,
        problemWhen: "no",
        adviceAboveThreshold: "Voice notes are rare. They can feel more personal than text.",
        adviceAboveThresholdRu: "Голосовых мало. Они звучат личнее, чем текст.",
      },
      {
        id: "scrolled-hour",
        title: "Scrolled social media hour+",
        titleRu: "Скроллил(а) соцсети больше часа",
        questionText: "Did I scroll social media for more than an hour?",
        questionTextRu: "Я сегодня скроллил(а) соцсети дольше часа?",
        category: "Social",
        answerType: "boolean",
        periodDays: 30,
        threshold: 15,
        problemWhen: "yes",
        adviceAboveThreshold: "Long scrolling is frequent. Set time limits.",
        adviceAboveThresholdRu: "Долгий скроллинг — частый. Поставь лимиты.",
      },
      {
        id: "like-mattered",
        title: "Got a like that mattered",
        titleRu: "Получил(а) важный лайк",
        questionText: "Did I get a like that mattered to me?",
        questionTextRu: "Мне сегодня пришёл лайк, который был для меня важен?",
        category: "Social",
        answerType: "boolean",
        periodDays: 30,
        threshold: 15,
        problemWhen: "yes",
        adviceAboveThreshold: "Likes matter often. Worth noticing why validation feels important.",
        adviceAboveThresholdRu: "Лайки важны часто. Стоит заметить, почему одобрение так значимо.",
      },
      {
        id: "commented-post",
        title: "Commented on someone's post",
        titleRu: "Оставил(а) комментарий",
        questionText: "Did I comment on someone's post?",
        questionTextRu: "Я сегодня оставил(а) комментарий под чужим постом?",
        category: "Social",
        answerType: "boolean",
        periodDays: 30,
        threshold: 20,
        problemWhen: "no",
        adviceAboveThreshold: "Engagement is low. Connection needs interaction.",
        adviceAboveThresholdRu: "Вовлечённость низкая. Связь нуждается во взаимодействии.",
      },
      {
        id: "checked-ex-profile",
        title: "Checked ex's profile",
        titleRu: "Заходил(а) в профиль бывшего/бывшей",
        questionText: "Did I check my ex's profile or stories?",
        questionTextRu: "Я сегодня заглядывал(а) в профиль или сторис бывшего/бывшей?",
        category: "Social",
        answerType: "boolean",
        periodDays: 30,
        threshold: 8,
        problemWhen: "yes",
        adviceAboveThreshold: "Checking ex's profiles is frequent. Consider blocking for peace.",
        adviceAboveThresholdRu: "Заглядываешь часто. Подумай о том, чтобы заблокировать — ради покоя.",
      },
    ],
  },
];

export interface LocalizedTemplate {
  id: string;
  title: string;
  questionText: string;
  category: Tracker["category"];
  subcategory?: string;
  answerType: AnswerType;
  periodDays: number;
  threshold: number;
  problemWhen: ProblemWhen;
  adviceAboveThreshold: string;
}

export const localizeTemplate = (tpl: LifeStreamTemplate): LocalizedTemplate => {
  const isRu = getLanguage() === "ru";
  return {
    id: tpl.id,
    title: isRu ? tpl.titleRu : tpl.title,
    questionText: isRu ? tpl.questionTextRu : tpl.questionText,
    category: tpl.category,
    subcategory: tpl.subcategory,
    answerType: tpl.answerType,
    periodDays: tpl.periodDays,
    threshold: tpl.threshold,
    problemWhen: tpl.problemWhen,
    adviceAboveThreshold: isRu ? tpl.adviceAboveThresholdRu : tpl.adviceAboveThreshold,
  };
};

export const localizeStream = (stream: LifeStream) => {
  const isRu = getLanguage() === "ru";
  return {
    ...stream,
    title: isRu ? stream.titleRu : stream.title,
    description: isRu ? stream.descriptionRu : stream.description,
  };
};

// Get 3-5 random templates for "Ideas of the day" (localized to active language)
export const getRandomIdeas = (count: number = 4): (LocalizedTemplate & { streamIcon: string; streamColor: string })[] => {
  const allTemplates = LIFE_STREAMS.flatMap(stream =>
    stream.templates.map(t => ({
      ...localizeTemplate(t),
      streamIcon: stream.icon,
      streamColor: stream.color,
    }))
  );
  const shuffled = [...allTemplates].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
};

// Static "trending" questions — also localized via localizeTemplate
const TRENDING_TEMPLATES_RAW: LifeStreamTemplate[] = [
  {
    id: "trending-1",
    title: "Spoke my truth",
    titleRu: "Говорил(а) свою правду",
    questionText: "Did you say what you really meant today?",
    questionTextRu: "Ты сегодня сказал(а) то, что на самом деле думал(а)?",
    category: "Voice",
    answerType: "boolean",
    periodDays: 30,
    threshold: 20,
    problemWhen: "no",
    adviceAboveThreshold: "You're often holding back. Small honest moments build courage.",
    adviceAboveThresholdRu: "Ты часто сдерживаешься. Маленькие честные моменты растят смелость.",
  },
  {
    id: "trending-2",
    title: "Felt loved",
    titleRu: "Чувствовал(а) себя любимым",
    questionText: "Did you feel loved today?",
    questionTextRu: "Ты чувствовал(а) себя сегодня любимым?",
    category: "Connections",
    answerType: "boolean",
    periodDays: 30,
    threshold: 15,
    problemWhen: "no",
    adviceAboveThreshold: "Love feels distant lately. Small gestures or open conversation might help.",
    adviceAboveThresholdRu: "Любовь кажется далёкой. Маленькие жесты или откровенный разговор могут помочь.",
  },
  {
    id: "trending-3",
    title: "Laughed really hard",
    titleRu: "Очень сильно смеялся(ась)",
    questionText: "Did you laugh so hard you cried or snorted?",
    questionTextRu: "Ты сегодня смеялся(ась) так, что плакал(а) или фыркал(а)?",
    category: "Fun",
    answerType: "boolean",
    periodDays: 30,
    threshold: 20,
    problemWhen: "no",
    adviceAboveThreshold: "Hard laughter is rare. Joy might need more space in your life.",
    adviceAboveThresholdRu: "Громкий смех редок. Радости нужно больше места в твоей жизни.",
  },
  {
    id: "trending-4",
    title: "Phone-free hour",
    titleRu: "Час без телефона",
    questionText: "Did you have at least one hour without your phone?",
    questionTextRu: "У тебя был сегодня хотя бы один час без телефона?",
    category: "Social",
    answerType: "boolean",
    periodDays: 30,
    threshold: 20,
    problemWhen: "no",
    adviceAboveThreshold: "Phone is always present. Even one hour off can feel refreshing.",
    adviceAboveThresholdRu: "Телефон всегда рядом. Даже один час без него освежает.",
  },
  {
    id: "trending-5",
    title: "Brain fog",
    titleRu: "Туман в голове",
    questionText: "Did you feel noticeable brain fog today?",
    questionTextRu: "Чувствовал(а) ли ты сегодня заметный туман в голове?",
    category: "Emotions",
    answerType: "boolean",
    periodDays: 30,
    threshold: 15,
    problemWhen: "yes",
    adviceAboveThreshold: "Brain fog is frequent. Check sleep, stress levels, or nutrition.",
    adviceAboveThresholdRu: "Туман в голове частый. Проверь сон, уровень стресса и питание.",
  },
];

// Public export: raw templates (for title/question lookup maps)
export const TRENDING_TEMPLATES_SOURCE = TRENDING_TEMPLATES_RAW;

// Public export: localized for rendering (call at render time so language changes apply)
export const getTrendingTemplates = (): LocalizedTemplate[] =>
  TRENDING_TEMPLATES_RAW.map(localizeTemplate);
